#define APPLICATION_NAME @"appfirst"
#define DEFAULT_USER_NAME_KEY @"AppFirstDefaultUserName"

#define DATA_NAME @"data"

#define CPU_RESOURCE_NAME @"cpu"
#define MEMORY_RESOURCE_NAME @"mem"
#define DISK_RESOURCE_NAME @"disk"


#define RESOURCE_VALUE_NAME @"values"
#define RESOURCE_TOTAL_NAME @"total"
#define RESOURCE_NAME_NAME @"names"
#define RESOURCE_TIME_NAME @"time"

#define ALERT_TYPE_NAME @"Type"
#define ALERT_STATUS_NAME @"Enabled"
#define ALERT_TARGET_NAME @"Target"
#define AlERT_LAST_TRIGGER_NAME @"Last Triggered"
#define ALERT_TRIGGER_TYPE_NAME @"Trigger"
#define ALERT_NAME @"Name"
#define ALERT_VALUE_NAME @"Value"
#define ALERT_RESET_NAME @"Reset"

#define AF_BAR_WIDTH 160.0
#define AF_BAR_HEIGHT 15.0

#define AF_VERTICAL_BAR_HEIGHT 95.0
#define AF_VERTICAL_BAR_WIDTH 20.0

#define AF_LEGEND_HEIGHT 10.0
#define AF_LEGEND_WIDTH 10.0

#define IPAD_SCREEN_WIDTH 768
#define IPAD_SCREEN_HEIGHT 1024
#define IPAD_LOADER_SIZE 40
#define IPAD_NAVIGATION_TITLE_WIDTH 400
#define IPAD_NAVIGATION_TITLE_HEIGHT 40
#define IPAD_TITLE_BIG_FONTSIZE 25
#define IPAD_TABLE_CELL_BIG_FONTSIZE 15
#define IPAD_TABLE_CELL_NORMAL_FONTSIZE 12
#define IPAD_TITLE_NORMAL_FONTSIZE 11
#define IPAD_TEXT_NORMAL_FONTSIZE 10
#define IPAD_DETAIL_VIEW_MARGIN 5
#define IPAD_DETAIL_VIEW_FIRST_COLUMN_WIDTH 250
#define IPAD_DETAIL_VIEW_SEPARATION_DIV_WIDTH 5
#define IPAD_WIDGET_INTERNAL_PADDING 5
#define IPAD_SPLITTER_DIV_WIDTH 15
#define IPAD_WIDGET_SECTION_TITLE_HEIGHT 20


#define IPHONE_SCREEN_WIDTH 320
#define IPHONE_SCREEN_HEIGHT 480
#define IPHONE_LOADER_SIZE 25
#define IPHONE_NAVIGATION_TITLE_WIDTH 250
#define IPHONE_NAVIGATION_TITLE_HEIGHT 30
#define IPHONE_TITLE_BIG_FONTSIZE 20
#define IPHONE_TITLE_NORMAL_FONTSIZE 9

#define MATRICS_TABLE_WIDTH 250
#define PROCESS_TABLE_HEIGHT 310
#define IPAD_SECOND_TABLE_PORTRAIT_HEIGHT 581
#define IPAD_SECOND_TABLE_LANDSCAPE_HEIGHT 325


#define DISK_CHART_WIDTH 120
#define DISK_CHART_HEIGHT 120

#define IPAD_DISK_PIE_WIDTH 60
#define IPAD_DISK_PIE_HEIGHT 60

#define CPU_LABEL_WIDTH 50
#define ALERT_CELL_HEIGHT 40
#define ALERT_CELL_WIDTH 300

#define ALERT_TAB_NORMAL_FONT_SIZE 13.5
#define DASHBOARD_TAB_NORMAL_FONT_SIZE 12
#define DASHBOARD_TAB_SMALL_FONT_SIZE 10.5

#define DEV_SERVER_IP @"https://192.168.1.102"
#define PROD_SERVER_IP @"https://wwws.appfirst.com"

#define LOGIN_API_STRING @"/api/iphone/login/"
#define SERVER_LIST_API_STRING @"/api/topology/data/node/"
#define ALERT_LIST_API_STRING @"/api/iphone/alertlist/"
#define ALERT_EDIT_API_STRING @"/api/iphone/alert/edit/"

#define PI 3.14159265358979323846

#define DEBUGGING NO

//UIColor backgroundGradientColor1 = [UIColor colorWithRed:202 green:202 blue:202 alpha:0.9] ;
//UIColor backgroundGradientColor2 = [UIColor colorWithRed:239 green:239 blue:239 alpha:1];

